# Jekyll site settings
title: Andriy Nikitin's Blog
description: >-
  Personal blog covering technology, reflections, and insights.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://andmerlin.github.io" # the base hostname & protocol for your site
github_username: andmerlin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files/folders
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
